print("Welcome to the band name creator !")
name =input("What is the name of your hometown?: \n")
pet = input("What is the name of your pet?: \n")
print("The name of your band is " + name + " " + pet)
print("Thank you for using our tool!")